# -*- coding: utf-8 -*-
"""model building

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dzCZrF1h6RE1dSPuYBxZXig8aF1Wl6LM
"""

import pandas as pd

df = pd.read_csv("/content/Salary_Data.csv")

df

df.info()

for column in df.columns:
    if df[column].isnull().any():
        if df[column].dtype == 'object':
            # Impute categorical columns with mode
            df[column] = df[column].fillna(df[column].mode()[0])
        else:
            # Impute numerical columns with mean
            df[column] = df[column].fillna(df[column].mean())

print("DataFrame after null value imputation:")
df.info()

df.duplicated().sum()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for column in ['Gender', 'Education Level', 'Job Title']:
    if column in df.columns:
        # Handle NaN values by filling with a placeholder or dropping if necessary
        # For now, let's fill with 'Unknown' before encoding
        df[column] = df[column].fillna('Unknown')
        df[column] = le.fit_transform(df[column])

print("DataFrame after Label Encoding:")
print(df.head())

# Drop rows with any NaN values from the DataFrame to ensure clean data for modeling
df.dropna(inplace=True)

X = df.drop('Salary', axis=1)
y = df['Salary']

print("Input features (X) shape:", X.shape)
print("Output variable (y) shape:", y.shape)
print("\nFirst 5 rows of X:\n", X.head())
print("\nFirst 5 values of y:\n", y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# Initialize models
models = {
    'Linear Regression': LinearRegression(),
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42),
    'SVM': SVR(),
    'KNN': KNeighborsRegressor()
}

results = {}

for name, model in models.items():
    print(f"\n--- Training {name} ---")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)

    results[name] = {'R2 Score': r2, 'MAE': mae, 'MSE': mse}

    print(f"{name} R-squared: {r2:.4f}")
    print(f"{name} Mean Absolute Error: {mae:.2f}")
    print(f"{name} Mean Squared Error: {mse:.2f}")

print("\n--- Model Performance Summary ---")
for name, metrics in results.items():
    print(f"\n{name}:")
    for metric_name, value in metrics.items():
        print(f"  {metric_name}: {value:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Convert results dictionary to a DataFrame for easier plotting
results_df = pd.DataFrame(results).T

plt.figure(figsize=(15, 5))

# Plot R2 Score
plt.subplot(1, 3, 1)
sns.barplot(x=results_df.index, y='R2 Score', data=results_df, palette='viridis', hue=results_df.index, legend=False)
plt.title('Model R2 Score Comparison')
plt.ylabel('R2 Score')
plt.xticks(rotation=45, ha='right')

# Plot Mean Absolute Error (MAE)
plt.subplot(1, 3, 2)
sns.barplot(x=results_df.index, y='MAE', data=results_df, palette='viridis', hue=results_df.index, legend=False)
plt.title('Model Mean Absolute Error (MAE) Comparison')
plt.ylabel('MAE')
plt.xticks(rotation=45, ha='right')

# Plot Mean Squared Error (MSE)
plt.subplot(1, 3, 3)
sns.barplot(x=results_df.index, y='MSE', data=results_df, palette='viridis', hue=results_df.index, legend=False)
plt.title('Model Mean Squared Error (MSE) Comparison')
plt.ylabel('MSE')
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()

import pickle

# Identify the best model based on R2 Score (or other preferred metric)
best_model_name = max(results, key=lambda name: results[name]['R2 Score'])
best_model = models[best_model_name]

# Define the filename for the pickled model
filename = best_model_name.replace(' ', '') + '.pkl'

# Save the best model to a .pkl file
with open(filename, 'wb') as file:
    pickle.dump(best_model, file)

print(f"The best model, '{best_model_name}', has been saved as '{filename}'.")

import pickle

# Save the fitted LabelEncoder object
with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(le, file)

print("LabelEncoder has been saved as 'label_encoder.pkl'.")

!pip install streamlit
import streamlit as st
import pandas as pd
import pickle
from sklearn.preprocessing import LabelEncoder

st.set_page_config(layout="wide")

# --- Load Model and Preprocessors ---
@st.cache_resource
def load_model():
    with open('RandomForest.pkl', 'rb') as file:
        model = pickle.load(file)
    return model

@st.cache_resource
def load_data_and_encoders():
    # Load the original CSV to get true categorical values and re-create encoders
    original_df = pd.read_csv("/content/Salary_Data.csv")

    # Ensure consistency with how NaNs were handled before encoding in the notebook
    categorical_cols = ['Gender', 'Education Level', 'Job Title']
    for col in categorical_cols:
        original_df[col] = original_df[col].fillna('Unknown')

    label_encoders = {}
    for col in categorical_cols:
        le_temp = LabelEncoder()
        # Fit on unique values after NaN imputation
        le_temp.fit(original_df[col].astype(str).unique()) # Use .astype(str) to handle potential mixed types safely
        label_encoders[col] = le_temp

    # Get the unique original categories for display in selectbox
    gender_options = original_df['Gender'].unique().tolist()
    education_options = original_df['Education Level'].unique().tolist()
    job_options = original_df['Job Title'].unique().tolist()

    return label_encoders, gender_options, education_options, job_options

# Load assets
model = load_model()
label_encoders, gender_options, education_options, job_options = load_data_and_encoders()

# Get feature columns in the order the model expects
# This order is crucial. Based on df.drop('Salary', axis=1) in notebook, it was:
feature_columns = ['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience']

# --- Streamlit App ---1
st.title("Salary Prediction Dashboard")
st.write("Enter the details below to predict the salary.")

with st.sidebar:
    st.header("Input Features")
    age = st.slider("Age", min_value=18, max_value=70, value=30)
    gender_raw = st.selectbox("Gender", options=gender_options)
    education_raw = st.selectbox("Education Level", options=education_options)
    job_title_raw = st.selectbox("Job Title", options=job_options)
    years_of_experience = st.slider("Years of Experience", min_value=0, max_value=40, value=5)

    # Display selected categorical values (as requested for 'colours on the dashboard' - simple display)
    st.markdown("--- Chosen Categorical Values ---")
    st.write(f"**Gender**: {gender_raw}")
    st.write(f"**Education Level**: {education_raw}")
    st.write(f"**Job Title**: {job_title_raw}")

    predict_button = st.button("Predict Salary")

if predict_button:
    # Preprocess inputs
    processed_gender = label_encoders['Gender'].transform([gender_raw])[0]
    processed_education = label_encoders['Education Level'].transform([education_raw])[0]
    processed_job_title = label_encoders['Job Title'].transform([job_title_raw])[0]

    # Create a DataFrame for prediction, ensuring column order matches training data
    input_data = pd.DataFrame([[age, processed_gender, processed_education, processed_job_title, years_of_experience]],
                                columns=feature_columns)

    # Make prediction
    prediction = model.predict(input_data)[0]

    st.success(f"The predicted salary is: ${prediction:,.2f}")
else:
    st.info("Adjust the input features in the sidebar and click 'Predict Salary'.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import pickle
# from sklearn.preprocessing import LabelEncoder
# import numpy as np
# 
# st.set_page_config(layout="wide")
# 
# # --- Load Model and Preprocessors ---
# @st.cache_resource
# def load_model():
#     with open('RandomForest.pkl', 'rb') as file:
#         model = pickle.load(file)
#     return model
# 
# @st.cache_resource
# def load_data_and_encoders():
#     # Load the original CSV to get true categorical values and re-create encoders
#     # Make sure 'Salary_Data.csv' is available in the deployment environment or adjust path
#     original_df = pd.read_csv("Salary_Data.csv")
# 
#     # Ensure consistency with how NaNs were handled before encoding in the notebook
#     categorical_cols = ['Gender', 'Education Level', 'Job Title']
#     for col in categorical_cols:
#         original_df[col] = original_df[col].fillna('Unknown')
# 
#     label_encoders = {}
#     for col in categorical_cols:
#         le_temp = LabelEncoder()
#         # Fit on unique values after NaN imputation
#         # Use .astype(str) to handle potential mixed types safely
#         le_temp.fit(original_df[col].astype(str).unique())
#         label_encoders[col] = le_temp
# 
#     # Get the unique original categories for display in selectbox
#     gender_options = original_df['Gender'].unique().tolist()
#     education_options = original_df['Education Level'].unique().tolist()
#     job_options = original_df['Job Title'].unique().tolist()
# 
#     return label_encoders, gender_options, education_options, job_options
# 
# # Load assets
# model = load_model()
# label_encoders, gender_options, education_options, job_options = load_data_and_encoders()
# 
# # Get feature columns in the order the model expects
# # This order is crucial. Based on df.drop('Salary', axis=1) in notebook, it was:
# feature_columns = ['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience']
# 
# # --- Streamlit App ---
# st.title("Salary Prediction Dashboard")
# st.write("Enter the details below to predict the salary.")
# 
# with st.sidebar:
#     st.header("Input Features")
#     age = st.slider("Age", min_value=18, max_value=70, value=30)
#     gender_raw = st.selectbox("Gender", options=gender_options)
#     education_raw = st.selectbox("Education Level", options=education_options)
#     job_title_raw = st.selectbox("Job Title", options=job_options)
#     years_of_experience = st.slider("Years of Experience", min_value=0, max_value=40, value=5)
# 
#     # Display selected categorical values
#     st.markdown("--- Chosen Categorical Values ---")
#     st.write(f"**Gender**: {gender_raw}")
#     st.write(f"**Education Level**: {education_raw}")
#     st.write(f"**Job Title**: {job_title_raw}")
# 
#     predict_button = st.button("Predict Salary")
# 
# if predict_button:
#     # Preprocess inputs
#     processed_gender = label_encoders['Gender'].transform([gender_raw])[0]
#     processed_education = label_encoders['Education Level'].transform([education_raw])[0]
#     processed_job_title = label_encoders['Job Title'].transform([job_title_raw])[0]
# 
#     # Create a DataFrame for prediction, ensuring column order matches training data
#     input_data = pd.DataFrame([[age, processed_gender, processed_education, processed_job_title, years_of_experience]],
#                                 columns=feature_columns)
# 
#     # Make prediction
#     prediction = model.predict(input_data)[0]
# 
#     st.success(f"The predicted salary is: ${prediction:,.2f}")
# else:
#     st.info("Adjust the input features in the sidebar and click 'Predict Salary'.")
# 
# 
# %%writefile requirements.txt
# streamlit
# pandas
# scikit-learn
# numpy
# matplotlib
# seaborn
#

